language: php

# list of PHP version to test against
php:
  - 7.0
  - 7.1

sudo: false

# build only the specified branches
branches:
  only:
    - master
    - dev/3.x

before_script:
  - git reset --hard HEAD
  - mysql -e 'create database homestead_test;'
  - cp example.env .env
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - php artisan key:generate

script: vendor/bin/phpunit --verbose