language: php

# list of PHP version to test against
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

sudo: false

# build only the specified branches
branches:
  only:
    - master
    - develop

before_script:
  - git reset --hard HEAD
  - mysql -e 'create database homestead_test;'
  - touch .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose